language: julia
os:
  - linux
julia:
  - 0.5
  - nightly
notifications:
  email: false
before_install:
  - if [ `uname` = "Linux" ]; then
      sudo apt-get install gfortran -y;
    elif [ `uname` = "Darwin" ]; then
      brew install gcc;
    fi
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.test("Lasso"; coverage=true)'; else julia -e 'Pkg.clone(pwd()); Pkg.test("Lasso")'; fi
after_success:
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("Lasso")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
